name: Create Tag

on:
  push:
    branches:
      - develop

permissions:
  contents: write

env:
  PATTERN: '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  create:
    if: ${{ startsWith( github.event.head_commit.message, 'Bump version to ' ) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WF_TOKEN }}

      - name: Tag and Push
        shell: bash
        run: |
          MESSAGE="${{ github.event.head_commit.message }}"
          VERSION="$(echo $MESSAGE | grep -oE $PATTERN)"

          git tag "v$VERSION"
          git push --tags
