name: WPORG Pre-Release

on:
  push:
    branches:
      - next

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          composer install --no-dev
          git add -f vendor

      - uses: kermage/action-wp-plugin-releaser@latest
        id: release
        with:
          dryrun: true

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.release.outputs.plugin-slug }}
          path: ${{ steps.release.outputs.export-dir }}
          include-hidden-files: true
