name: WPORG Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          composer install --no-dev
          git add -f vendor

      - uses: kermage/action-wp-plugin-releaser@latest
        id: release
        env:
          WPORG_USERNAME: ${{ secrets.WPORG_USERNAME }}
          WPORG_PASSWORD: ${{ secrets.WPORG_PASSWORD }}

      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.release.outputs.plugin-zip }}
